<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6WmxG2Y\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6WmxG2Y/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6WmxG2Y.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6WmxG2Y\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6WmxG2Y\App_KernelDevDebugContainer([
    'container.build_hash' => '6WmxG2Y',
    'container.build_id' => 'e8708e78',
    'container.build_time' => 1718721993,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container6WmxG2Y');
